version: "2"
services: 
 
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "5883:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency
    volumes: 
      - ./my-datavolume:/docker-entrypoint-initdb.d/:ro
      - ./my_datavolume:/var/lib/mysql
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8584:80"